### ISSUE TITLE
Overflow on support Screen

### ISSUE THREAD

**Issue by ShadrackOngera** [surtecha/karman#31]
There is an overflow on the support screen

**Comment by surtecha** [comment]
Hi! Could you please share a screenshot of the issue that you're facing?

**Comment by ShadrackOngera** [comment]
Hello Here is the screenshot. 

can I create a Pull request for the same?
![WhatsApp Image 2024-10-11 at 2 14 15 PM](https://github.com/user-attachments/assets/8c08c1d7-b3d8-46f7-901c-21b0770e0ac3)

**Comment by surtecha** [comment]
Hello. The issue has been patched. Please stay tuned for the upcoming update. Thank you for your patience!
